# Generated by Django 5.1.2 on 2024-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_liveprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='popluar_assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('etf', 'ETF')], max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LivePrice',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
